apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: spring-microservices-staging
spec:
  ports:
    - port: 8080
  selector:
    app: cart-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: spring-microservices-staging
spec:
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: kaingyn615/cart-service:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka:password@discovery-server:8761/eureka/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: cart-service
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017/cart-service
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: spring-microservices-staging
spec:
  ports:
    - port: 8080
  selector:
    app: payment-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: spring-microservices-staging
spec:
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: kaingyn615/payment-service:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka:password@discovery-server:8761/eureka/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: payment-service
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: broker:9092
            - name: VNPAY_TMN_CODE
              value: "G18S515I"
            - name: VNPAY_HASH_SECRET
              value: "8VPOINLIUTBYIMFPUZSQFWRFHNJ99415"
          ports:
            - containerPort: 8080
