apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: spring-microservices-staging
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: spring-microservices-staging
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: kaingyn615/frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
