apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
  namespace: spring-microservices-staging
data:
  realm-export.json: |
    {
        "id": "spring-boot-microservices-realm",
        "realm": "spring-boot-microservices-realm",
        "enabled": true,
        "registrationAllowed": true,
        "roles": {
          "realm": [
            { "name": "ADMIN", "description": "Admin role" },
            { "name": "USER", "description": "User role" }
          ]
        },
        "clients": [
          {
            "clientId": "spring-cloud-client",
            "secret": "**********",
            "serviceAccountsEnabled": true,
            "publicClient": false,
            "protocol": "openid-connect"
          },
          {
            "clientId": "frontend-client",
            "enabled": true,
            "publicClient": true,
            "protocol": "openid-connect",
            "redirectUris": ["*"],
            "webOrigins": ["*"]
          }
        ]
    }
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: spring-microservices-staging
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31081
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: spring-microservices-staging
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:18.0.0
          args: ["start-dev", "--import-realm"]
          env:
            - name: DB_VENDOR
              value: MYSQL
            - name: DB_ADDR
              value: keycloak-mysql
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              value: keycloak
            - name: DB_PASSWORD
              value: password
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import/realm-export.json
              subPath: realm-export.json
      volumes:
        - name: realm-config
          configMap:
            name: keycloak-realm
