apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - databases.yaml
  - kafka-zipkin.yaml
  - keycloak.yaml
  - canary-rollouts.yaml
  - ecommerce-expansion.yaml
  - services.yaml
  - frontend.yaml
  - ingress/ingress.yaml
  - ingress/cert-issuer.yaml
  - monitoring/namespace.yaml
  - monitoring/prometheus-deployment.yaml
  - monitoring/prometheus-config.yaml
  - monitoring/grafana.yaml

images:
  - name: hiunehihi/product-service
    newTag: dev
  - name: hiunehihi/cart-service
    newTag: dev
  - name: hiunehihi/payment-service
    newTag: dev
  - name: hiunehihi/discovery-server
    newTag: dev
  - name: hiunehihi/api-gateway
    newTag: dev
  - name: hiunehihi/order-service
    newTag: dev
  - name: hiunehihi/inventory-service
    newTag: dev
  - name: hiunehihi/notification-service
    newTag: dev
  - name: hiunehihi/admin-server
    newTag: dev
  - name: hiunehihi/frontend
    newTag: dev
