apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: product-service
  namespace: spring-microservices
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: spring-microservices
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: spring-microservices
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: spring-microservices
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: spring-microservices
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: spring-microservices
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: spring-microservices
spec:
  replicas: 1
