apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: spring-microservices-dev
type: Opaque
stringData:
  postgres-order-password: change-me
  postgres-inventory-password: change-me
  keycloak-db-password: change-me
  keycloak-admin-password: change-me
  keycloak-mysql-root-password: change-me
  keycloak-mysql-password: change-me
  vnpay-tmn-code: change-me
  vnpay-hash-secret: change-me
  eureka-default-zone: http://eureka:change-me@discovery-server:8761/eureka/
