apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - databases.yaml
  - kafka-zipkin.yaml
  - keycloak.yaml
  - canary-rollouts.yaml
  - ecommerce-expansion.yaml
  - services.yaml
  - frontend.yaml
  - ingress/ingress.yaml
  - ingress/cert-issuer.yaml
  - monitoring/namespace.yaml
  - monitoring/prometheus-rbac.yaml
  - monitoring/prometheus-config.yaml
  - monitoring/prometheus-deployment.yaml
  - monitoring/grafana.yaml
  - monitoring/alertmanager.yaml
images:
  - name: kaing615/product-service
    newTag: main
  - name: kaing615/cart-service
    newTag: main
  - name: kaing615/payment-service
    newTag: main
  - name: kaing615/discovery-server
    newTag: main
  - name: kaing615/api-gateway
    newTag: main
  - name: kaing615/order-service
    newTag: main
  - name: kaing615/inventory-service
    newTag: main
  - name: kaing615/notification-service
    newTag: main
  - name: kaing615/admin-server
    newTag: main
  - name: kaing615/frontend
    newTag: main
