apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - databases.yaml
  - kafka-zipkin.yaml
  - keycloak.yaml
  - canary-rollouts.yaml
  - ecommerce-expansion.yaml
  - services.yaml
  - frontend.yaml
  - ingress/ingress.yaml
  - ingress/cert-issuer.yaml
  - monitoring/namespace.yaml
  - monitoring/prometheus-rbac.yaml
  - monitoring/prometheus-config.yaml
  - monitoring/prometheus-deployment.yaml
  - monitoring/grafana.yaml
  - monitoring/alertmanager.yaml
images:
  - name: hiunehihi/product-service
    digest: sha256:150f3b2d810d5e66e5be421807b5582d020c10f71e534908c2e76818b2a04fc2
  - name: hiunehihi/cart-service
    digest: sha256:8772cb452ed5846a1f2c385aae9fac554af43da5f8dfa50e72a207b5af99e1b8
  - name: hiunehihi/payment-service
    digest: sha256:e6ef8c1d4d422c6d1e523ee18ba748cbbdbb05a92fe9824c0b087d9670e5b031
  - name: hiunehihi/discovery-server
    digest: sha256:467a25929c863ecc92c60e9ec55b6c4f79318a039b6e89dd419eae3c3fdd999f
  - name: hiunehihi/api-gateway
    digest: sha256:9d55de6e6117dec5cddcfb9cc55518f1686620c3d62af0be954966f79b95b396
  - name: hiunehihi/order-service
    digest: sha256:35e4505215bd58dbc59c03c6457f0edffa31667a33bf23304f12c84e491ce2a6
  - name: hiunehihi/inventory-service
    digest: sha256:fc2b9342f93572685805b40996934c7fb610877e3ffd3e05bbc33c1d55c5e41a
  - name: hiunehihi/notification-service
    digest: sha256:cae08da61ed7be649150bad3aff79c1c8b0917a2d7372bcae39a37875e4ddc97
  - name: hiunehihi/admin-server
    digest: sha256:a27e1434f07ad80fae12947d5144cf0b1cd4c73d88e6ccbf91ad88fd9e14bcf2
  - name: hiunehihi/frontend
    digest: sha256:7799d847eaff5e73c730f6be38665ff2b1c95d57f1db176ecc344a1d46b89259
