apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spring-microservices

resources:
  - namespace.yaml
  - ../../base
  - hpa.yaml

images:
  - name: hiunehihi/product-service
    newTag: main
  - name: hiunehihi/cart-service
    newTag: main
  - name: hiunehihi/payment-service
    newTag: main
  - name: hiunehihi/discovery-server
    newTag: main
  - name: hiunehihi/api-gateway
    newTag: main
  - name: hiunehihi/order-service
    newTag: main
  - name: hiunehihi/inventory-service
    newTag: main
  - name: hiunehihi/notification-service
    newTag: main
  - name: hiunehihi/admin-server
    newTag: main
  - name: hiunehihi/frontend
    newTag: main

patches:
  - path: ingress-hosts-patch.yaml
  - path: replicas-patch.yaml
