all:
  children:
    kube_control_plane:
      hosts:
                k3s-master-1:
          ansible_host: 3.85.27.167
          ansible_user: ubuntu
          
          internal_address: 172.31.28.235
                  
    kube_node:
      hosts:
                k3s-worker-1:
          ansible_host: 54.90.159.160
          ansible_user: ubuntu
          
          internal_address: 172.31.33.246
                          k3s-worker-2:
          ansible_host: 98.92.140.135
          ansible_user: ubuntu
          
          internal_address: 172.31.11.90
                  
    etcd:
      hosts:
                k3s-master-1:
          ansible_host: 3.85.27.167
        
    k8s_cluster:
      children:
        kube_control_plane: {}
        kube_node: {}

    serivce_cluster: {}
